"""initial

Revision ID: 0001
Revises:
Create Date: 2026-10-04 22:05:19.319806

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=True),
        sa.Column("object_id", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(
        op.f("ix_audit_log_object_type_object_id"), "audit_log", ["object_type", "object_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_user_id_at"), "audit_log", ["user_id", "at"], unique=False)
    op.create_table(
        "scan_dedup",
        sa.Column("client_scan_id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("client_scan_id", name=op.f("pk_scan_dedup")),
    )
    op.create_table(
        "setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retention_raw_days", sa.Integer(), server_default="30", nullable=False),
        sa.Column("retention_clip_days", sa.Integer(), server_default="90", nullable=False),
        sa.Column("session_warn_minutes", sa.Integer(), server_default="15", nullable=False),
        sa.Column("session_abandon_minutes", sa.Integer(), server_default="30", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_setting_single_row")),
        sa.CheckConstraint("retention_clip_days >= retention_raw_days", name=op.f("ck_setting_clip_ge_raw")),
        sa.CheckConstraint("retention_clip_days BETWEEN 1 AND 365", name=op.f("ck_setting_clip_days_range")),
        sa.CheckConstraint("retention_raw_days BETWEEN 1 AND 365", name=op.f("ck_setting_raw_days_range")),
        sa.CheckConstraint(
            "session_abandon_minutes > session_warn_minutes", name=op.f("ck_setting_abandon_gt_warn")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setting")),
    )
    op.create_table(
        "shop",
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("platform_shop_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("auth_status", sa.Text(), server_default="DISCONNECTED", nullable=False),
        sa.Column("access_token_enc", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token_enc", sa.LargeBinary(), nullable=True),
        sa.Column("auth_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_cursor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "auth_status IN ('CONNECTED', 'EXPIRED', 'DISCONNECTED')", name=op.f("ck_shop_auth_status_enum")
        ),
        sa.CheckConstraint("platform IN ('SHOPEE')", name=op.f("ck_shop_platform_enum")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop")),
        sa.UniqueConstraint("platform", "platform_shop_id", name=op.f("uq_shop_platform_platform_shop_id")),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("failed_logins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "role IN ('ADMIN', 'SUPERVISOR', 'CSKH', 'STATION')", name=op.f("ck_user_role_enum")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index("uq_user_username_lower", "user", [sa.literal_column("lower(username)")], unique=True)
    op.create_table(
        "csv_import",
        sa.Column("status", sa.Text(), server_default="PREVIEW", nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preview_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PREVIEW', 'COMMITTED', 'REJECTED', 'EXPIRED')",
            name=op.f("ck_csv_import_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("fk_csv_import_created_by_user"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_csv_import")),
    )
    op.create_index(op.f("ix_csv_import_created_at"), "csv_import", ["created_at"], unique=False)
    op.create_table(
        "refresh_token",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("client", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("client IN ('STATION', 'DASHBOARD')", name=op.f("ck_refresh_token_client_enum")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_refresh_token_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_token_token_hash")),
    )
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.create_table(
        "station",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("account_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_user_id"],
            ["user.id"],
            name=op.f("fk_station_account_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_station")),
        sa.UniqueConstraint("account_user_id", name=op.f("uq_station_account_user_id")),
    )
    op.create_index("uq_station_name_lower", "station", [sa.literal_column("lower(name)")], unique=True)
    op.create_table(
        "camera",
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("rtsp_url", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("password_enc", sa.LargeBinary(), nullable=True),
        sa.Column("mediamtx_path", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="OFFLINE", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clock_offset_ms", sa.Integer(), nullable=True),
        sa.Column("roi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("role IN ('CAM1', 'CAM2')", name=op.f("ck_camera_role_enum")),
        sa.CheckConstraint("status IN ('ONLINE', 'OFFLINE')", name=op.f("ck_camera_status_enum")),
        sa.ForeignKeyConstraint(
            ["station_id"], ["station.id"], name=op.f("fk_camera_station_id_station"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_camera")),
        sa.UniqueConstraint("station_id", "role", name=op.f("uq_camera_station_id_role")),
    )
    op.create_table(
        "order",
        sa.Column("shop_id", sa.UUID(), nullable=True),
        sa.Column("platform_order_sn", sa.Text(), nullable=False),
        sa.Column("platform_status", sa.Text(), nullable=True),
        sa.Column("buyer_note", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), server_default="API", nullable=False),
        sa.Column("csv_import_id", sa.UUID(), nullable=True),
        sa.Column("created_at_platform", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("source IN ('API', 'CSV')", name=op.f("ck_order_source_enum")),
        sa.ForeignKeyConstraint(
            ["csv_import_id"],
            ["csv_import.id"],
            name=op.f("fk_order_csv_import_id_csv_import"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shop.id"], name=op.f("fk_order_shop_id_shop"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
        sa.UniqueConstraint("platform_order_sn", name=op.f("uq_order_platform_order_sn")),
    )
    op.create_table(
        "order_item",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.Text(), nullable=True),
        sa.Column("product_name", sa.Text(), nullable=False),
        sa.Column("variation", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_item_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("fk_order_item_order_id_order"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_item")),
    )
    op.create_index(op.f("ix_order_item_order_id"), "order_item", ["order_id"], unique=False)
    op.create_table(
        "package",
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("tracking_number", sa.Text(), nullable=False),
        sa.Column("warehouse_status", sa.Text(), server_default="NEW", nullable=False),
        sa.Column("platform_logistics_status", sa.Text(), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "warehouse_status IN ('NEW', 'PACKING', 'PACKED', 'HANDED_OVER', 'DELIVERED', 'CANCELLED', 'CANCELLED_AFTER_PACK')",
            name=op.f("ck_package_warehouse_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("fk_package_order_id_order"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package")),
    )
    op.create_index(
        op.f("ix_package_warehouse_status_updated_at"),
        "package",
        ["warehouse_status", "updated_at"],
        unique=False,
    )
    op.create_index(
        "uq_package_tracking_number_upper",
        "package",
        [sa.literal_column("upper(tracking_number)")],
        unique=True,
    )
    op.create_table(
        "video_segment",
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"], ["camera.id"], name=op.f("fk_video_segment_camera_id_camera"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_segment")),
        sa.UniqueConstraint("camera_id", "start_at", name=op.f("uq_video_segment_camera_id_start_at")),
    )
    op.create_index(
        op.f("ix_video_segment_camera_id_end_at"), "video_segment", ["camera_id", "end_at"], unique=False
    )
    op.create_table(
        "session",
        sa.Column("type", sa.Text(), server_default="PACK", nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("open_code", sa.Text(), nullable=False),
        sa.Column("close_code", sa.Text(), nullable=True),
        sa.Column("cam2_code", sa.Text(), nullable=True),
        sa.Column("flags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("supersedes_session_id", sa.UUID(), nullable=True),
        sa.Column("package_status_before", sa.Text(), nullable=True),
        sa.Column("status_before_approval", sa.Text(), nullable=True),
        sa.Column("mismatch", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cam2_seen_match", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("warn_notified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "cancel_reason IN ('OUT_OF_STOCK', 'WRONG_SCAN', 'OTHER', 'SUPERVISOR')",
            name=op.f("ck_session_cancel_reason_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'MISMATCH', 'WAITING_APPROVAL', 'COMPLETED', 'CANCELLED', 'ABANDONED', 'SUPERSEDED')",
            name=op.f("ck_session_status_enum"),
        ),
        sa.CheckConstraint("type IN ('PACK')", name=op.f("ck_session_type_enum")),
        sa.ForeignKeyConstraint(
            ["package_id"], ["package.id"], name=op.f("fk_session_package_id_package"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["station.id"], name=op.f("fk_session_station_id_station"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_session_id"],
            ["session.id"],
            name=op.f("fk_session_supersedes_session_id_session"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
    )
    op.create_index(op.f("ix_session_package_id"), "session", ["package_id"], unique=False)
    op.create_index(op.f("ix_session_started_at"), "session", ["started_at"], unique=False)
    op.create_index(
        op.f("ix_session_station_id_started_at"), "session", ["station_id", "started_at"], unique=False
    )
    op.create_index(
        "uq_session_active_package",
        "session",
        ["package_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('OPEN', 'MISMATCH', 'WAITING_APPROVAL')"),
    )
    op.create_index(
        "uq_session_active_station",
        "session",
        ["station_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('OPEN', 'MISMATCH', 'WAITING_APPROVAL')"),
    )
    op.create_table(
        "status_history",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "source IN ('PLATFORM', 'WAREHOUSE', 'MANUAL')", name=op.f("ck_status_history_source_enum")
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["package.id"],
            name=op.f("fk_status_history_package_id_package"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_status_history")),
    )
    op.create_index(
        op.f("ix_status_history_package_id_at"), "status_history", ["package_id", "at"], unique=False
    )
    op.create_table(
        "approval_request",
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("tracking_number", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "decision IN ('CONTINUE', 'CLOSE_WITH_NOTE', 'CANCEL_SESSION', 'APPROVE_REPACK', 'REJECT')",
            name=op.f("ck_approval_request_decision_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RESOLVED', 'WITHDRAWN')", name=op.f("ck_approval_request_status_enum")
        ),
        sa.CheckConstraint(
            "type IN ('MISMATCH', 'ASSIST', 'REPACK')", name=op.f("ck_approval_request_type_enum")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["user.id"], name=op.f("fk_approval_request_decided_by_user"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_approval_request_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["station.id"],
            name=op.f("fk_approval_request_station_id_station"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_request")),
    )
    op.create_index(
        "uq_approval_request_pending_station",
        "approval_request",
        ["station_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "clip",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("camera_role", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_s", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("sha256", sa.Text(), nullable=True),
        sa.Column("flags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("held", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("held_by", sa.UUID(), nullable=True),
        sa.Column("held_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("camera_role IN ('CAM1', 'CAM2')", name=op.f("ck_clip_camera_role_enum")),
        sa.CheckConstraint(
            "status IN ('PENDING', 'READY', 'FAILED', 'DELETED')", name=op.f("ck_clip_status_enum")
        ),
        sa.ForeignKeyConstraint(
            ["held_by"], ["user.id"], name=op.f("fk_clip_held_by_user"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], name=op.f("fk_clip_session_id_session"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clip")),
        sa.UniqueConstraint("session_id", "camera_role", name=op.f("uq_clip_session_id_camera_role")),
    )
    op.create_index(
        "ix_clip_retention_candidates",
        "clip",
        ["end_at"],
        unique=False,
        postgresql_where=sa.text("held = false AND status = 'READY'"),
    )
    op.create_table(
        "export",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("layout", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="QUEUED", nullable=False),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("path_video", sa.Text(), nullable=True),
        sa.Column("path_info", sa.Text(), nullable=True),
        sa.Column("sha256", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("layout IN ('CAM1', 'CAM2', 'SIDE_BY_SIDE')", name=op.f("ck_export_layout_enum")),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'READY', 'FAILED')", name=op.f("ck_export_status_enum")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("fk_export_created_by_user"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], name=op.f("fk_export_session_id_session"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export")),
    )
    op.create_index(
        op.f("ix_export_created_by_created_at"), "export", ["created_by", "created_at"], unique=False
    )
    op.create_table(
        "session_event",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_session_event_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_event")),
    )
    op.create_index(
        op.f("ix_session_event_session_id_at"), "session_event", ["session_id", "at"], unique=False
    )
    # ### end Alembic commands ###

    # Một dòng cấu hình duy nhất (02a §3).
    op.execute("INSERT INTO setting (id) VALUES (1)")

    # audit_log chỉ INSERT, với mọi user DB (NFR-15, DEC-40).
    op.execute(
        """
        CREATE FUNCTION audit_log_readonly() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log chỉ cho phép INSERT' USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_readonly()"
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log "
        "FOR EACH STATEMENT EXECUTE FUNCTION audit_log_readonly()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_readonly()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_event_session_id_at"), table_name="session_event")
    op.drop_table("session_event")
    op.drop_index(op.f("ix_export_created_by_created_at"), table_name="export")
    op.drop_table("export")
    op.drop_index(
        "ix_clip_retention_candidates",
        table_name="clip",
        postgresql_where=sa.text("held = false AND status = 'READY'"),
    )
    op.drop_table("clip")
    op.drop_index(
        "uq_approval_request_pending_station",
        table_name="approval_request",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("approval_request")
    op.drop_index(op.f("ix_status_history_package_id_at"), table_name="status_history")
    op.drop_table("status_history")
    op.drop_index(
        "uq_session_active_station",
        table_name="session",
        postgresql_where=sa.text("status IN ('OPEN', 'MISMATCH', 'WAITING_APPROVAL')"),
    )
    op.drop_index(
        "uq_session_active_package",
        table_name="session",
        postgresql_where=sa.text("status IN ('OPEN', 'MISMATCH', 'WAITING_APPROVAL')"),
    )
    op.drop_index(op.f("ix_session_station_id_started_at"), table_name="session")
    op.drop_index(op.f("ix_session_started_at"), table_name="session")
    op.drop_index(op.f("ix_session_package_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_video_segment_camera_id_end_at"), table_name="video_segment")
    op.drop_table("video_segment")
    op.drop_index("uq_package_tracking_number_upper", table_name="package")
    op.drop_index(op.f("ix_package_warehouse_status_updated_at"), table_name="package")
    op.drop_table("package")
    op.drop_index(op.f("ix_order_item_order_id"), table_name="order_item")
    op.drop_table("order_item")
    op.drop_table("order")
    op.drop_table("camera")
    op.drop_index("uq_station_name_lower", table_name="station")
    op.drop_table("station")
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index(op.f("ix_csv_import_created_at"), table_name="csv_import")
    op.drop_table("csv_import")
    op.drop_index("uq_user_username_lower", table_name="user")
    op.drop_table("user")
    op.drop_table("shop")
    op.drop_table("setting")
    op.drop_table("scan_dedup")
    op.drop_index(op.f("ix_audit_log_user_id_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_object_type_object_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
