# ruff: noqa: S608 — SQL ghép từ hằng id trong test, không có input ngoài
"""Migration 0003 `returns_recon_claims` trên dữ liệu Phase 1 (T-101; 02a §3, TC-MG.01, TC-MG.02).

Chạy trên DB riêng (`<TEST_DATABASE_URL>_mig`) để up / down / up không đụng DB test dùng chung.
Test đồng bộ: Alembic `env.py` tự `asyncio.run`, nên dữ liệu được ghi bằng `asyncio.run(...)` riêng.
"""

import asyncio
import os
from collections.abc import Iterator
from typing import Any

import pytest
from alembic import command
from alembic.util import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import create_async_engine

from aicam.core.settings import get_settings

from .conftest import TEST_DATABASE_URL, _ensure_database, _reset_schema, alembic_config

pytestmark = pytest.mark.integration

_BASE = make_url(TEST_DATABASE_URL)
MIG_URL = _BASE.set(database=f"{_BASE.database}_mig").render_as_string(hide_password=False)

PKG_PACKED = "01920000-0000-7000-8000-000000000001"
PKG_NEW = "01920000-0000-7000-8000-000000000002"
STATION = "01920000-0000-7000-8000-0000000000b1"
SESSION = "01920000-0000-7000-8000-0000000000d1"
CLIP = "01920000-0000-7000-8000-0000000000e1"


async def _exec(sql: str, params: dict[str, Any] | None = None) -> list[Any]:
    engine = create_async_engine(MIG_URL)
    try:
        async with engine.begin() as conn:
            result = await conn.execute(text(sql), params or {})
            return list(result.all()) if result.returns_rows else []
    finally:
        await engine.dispose()


def run(sql: str, params: dict[str, Any] | None = None) -> list[Any]:
    return asyncio.run(_exec(sql, params))


@pytest.fixture
def mig_db(migrated_database_url: str) -> Iterator[None]:
    """DB riêng ở revision 0002; trả lại `DATABASE_URL` của DB test dùng chung sau test."""
    asyncio.run(_ensure_database(MIG_URL))
    asyncio.run(_reset_schema(MIG_URL))
    os.environ["DATABASE_URL"] = MIG_URL
    get_settings.cache_clear()
    try:
        command.upgrade(alembic_config(), "0002")
        yield
    finally:
        os.environ["DATABASE_URL"] = migrated_database_url
        get_settings.cache_clear()


def _seed_phase1(retention_clip_days: int) -> None:
    run(
        "UPDATE setting SET retention_raw_days = 30, retention_clip_days = :d",
        {"d": retention_clip_days},
    )
    statements = [
        f"""INSERT INTO package (id, tracking_number, warehouse_status, updated_at) VALUES
          ('{PKG_PACKED}', 'SPXTST0000010', 'PACKED', now() - interval '3 days'),
          ('{PKG_NEW}', 'SPXTST0000012', 'NEW', now() - interval '5 days')""",
        f"""INSERT INTO status_history (id, package_id, source, from_status, to_status, at) VALUES
          ('01920000-0000-7000-8000-0000000000a1', '{PKG_PACKED}', 'WAREHOUSE', 'NEW', 'PACKING',
           now() - interval '2 days 1 hour'),
          ('01920000-0000-7000-8000-0000000000a2', '{PKG_PACKED}', 'WAREHOUSE', 'PACKING', 'PACKED',
           now() - interval '2 days')""",
        f"INSERT INTO station (id, name) VALUES ('{STATION}', 'TST Station 01')",
        f"""INSERT INTO session (id, package_id, station_id, status, started_at, ended_at, open_code)
          VALUES ('{SESSION}', '{PKG_PACKED}', '{STATION}', 'COMPLETED', now() - interval '2 days 1 hour',
                  now() - interval '2 days', 'SPXTST0000010')""",
        f"""INSERT INTO clip (id, session_id, camera_role, status, start_at, end_at, held)
          VALUES ('{CLIP}', '{SESSION}', 'CAM1', 'READY', now() - interval '2 days 1 hour',
                  now() - interval '2 days', true)""",
    ]
    for sql in statements:
        run(sql)


def test_upgrade_0003_on_phase1_data(mig_db: None) -> None:
    """TC-MG.01 + TC-MG.02: backfill mốc kiện, `recon_start_at`, retention 45 → 60 có audit, check sạch."""
    _seed_phase1(retention_clip_days=45)

    command.upgrade(alembic_config(), "0003")

    rows = {
        r[0]: r[1:]
        for r in run(
            "SELECT tracking_number, created_at = updated_at, status_changed_at, updated_at, is_placeholder "
            "FROM package"
        )
    }
    same_created, changed_packed, updated_packed, placeholder = rows["SPXTST0000010"]
    assert same_created
    assert not placeholder
    assert changed_packed > updated_packed  # lấy từ status_history (lần PACKED), không phải updated_at
    _, changed_new, updated_new, _ = rows["SPXTST0000012"]
    assert changed_new == updated_new  # không có lịch sử → updated_at

    (setting,) = run(
        "SELECT retention_clip_days, recon_start_at > now() - interval '1 minute', return_missing_days, "
        "return_warn_minutes, return_abandon_minutes FROM setting"
    )
    assert tuple(setting) == (60, True, 7, 20, 45)
    audit = run("SELECT action, data FROM audit_log WHERE action = 'RETENTION_RAISED_TO_MINIMUM'")
    assert [(a, d) for a, d in audit] == [
        ("RETENTION_RAISED_TO_MINIMUM", {"retention_clip_days": {"old": 45, "new": 60}})
    ]
    assert run("SELECT kind, work_mode, operator_name FROM station") == [("PACK", "PACK", None)]
    assert run("SELECT held FROM clip") == [(True,)]  # 0003 không đụng cờ giữ (0004 — T-111)

    # Mọi CHECK mới đã VALIDATE (không còn NOT VALID).
    assert run("SELECT conname FROM pg_constraint WHERE contype = 'c' AND NOT convalidated") == []
    # Model khớp DB (02a §3 "alembic check").
    command.check(alembic_config())


def test_upgrade_keeps_retention_above_minimum(mig_db: None) -> None:
    """DEC-257: retention ≥ sàn giữ nguyên, không audit."""
    _seed_phase1(retention_clip_days=90)

    command.upgrade(alembic_config(), "0003")

    assert run("SELECT retention_clip_days FROM setting") == [(90,)]
    assert run("SELECT count(*) FROM audit_log WHERE action = 'RETENTION_RAISED_TO_MINIMUM'") == [(0,)]


def test_new_checks_accept_phase2_values_and_reject_bad_ones(mig_db: None) -> None:
    command.upgrade(alembic_config(), "0003")
    _seed_phase1(retention_clip_days=90)

    run(f"UPDATE package SET warehouse_status = 'RETURN_EXPECTED' WHERE id = '{PKG_NEW}'")
    run(
        "UPDATE station SET kind = 'BOTH', work_mode = 'RETURN', operator_name = 'Lan' "
        f"WHERE id = '{STATION}'"
    )
    (code,) = run(
        "INSERT INTO return_case (id, kind, status, source) "
        "VALUES ('01920000-0000-7000-8000-0000000000c1', 'UNANNOUNCED', 'EXPECTED', 'WAREHOUSE') "
        "RETURNING code"
    )
    assert code[0] == "HH-000001"
    assert run("SELECT nextval('placeholder_code_seq'), nextval('claim_code_seq')") == [(1, 1)]

    bad = [
        f"UPDATE station SET kind = 'PACK', work_mode = 'RETURN' WHERE id = '{STATION}'",
        f"UPDATE station SET operator_name = 'L' WHERE id = '{STATION}'",
        f"UPDATE package SET warehouse_status = 'MISMATCH' WHERE id = '{PKG_NEW}'",
        "UPDATE setting SET return_abandon_minutes = 10, return_warn_minutes = 20",
        # Phiên PACK không được gắn hồ sơ hàng hoàn.
        f"UPDATE session SET return_case_id = '01920000-0000-7000-8000-0000000000c1' WHERE id = '{SESSION}'",
    ]
    for sql in bad:
        with pytest.raises(IntegrityError):
            run(sql)


def test_downgrade_then_upgrade_without_phase2_data(mig_db: None) -> None:
    """Up → down → up giữ dữ liệu Phase 1; CHECK về tập cũ khi down."""
    _seed_phase1(retention_clip_days=45)
    cfg = alembic_config()
    command.upgrade(cfg, "0003")

    command.downgrade(cfg, "0002")

    assert run("SELECT count(*) FROM package") == [(2,)]
    assert run("SELECT held FROM clip") == [(True,)]
    assert run("SELECT to_regclass('return_case'), to_regclass('claim_code_seq')") == [(None, None)]
    (definition,) = run(
        "SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = 'ck_session_type_enum'"
    )
    assert "RETURN" not in definition[0]
    assert run("SELECT retention_clip_days FROM setting") == [(60,)]  # không hạ lại dưới sàn

    command.upgrade(cfg, "head")
    command.check(cfg)


def test_downgrade_refused_when_phase2_data_exists(mig_db: None) -> None:
    """DEC-301: downgrade cấu trúc không được làm mất dữ liệu Phase 2 (archive ở T-120)."""
    cfg = alembic_config()
    command.upgrade(cfg, "0003")
    run(
        "INSERT INTO return_case (id, kind, status, source) "
        "VALUES ('01920000-0000-7000-8000-0000000000c2', 'UNANNOUNCED', 'EXPECTED', 'WAREHOUSE')"
    )

    with pytest.raises(RuntimeError, match="return_case=1"):
        command.downgrade(cfg, "0002")

    assert run("SELECT version_num FROM alembic_version") == [("0003",)]
    assert run("SELECT count(*) FROM return_case") == [(1,)]


def test_alembic_check_detects_drift(mig_db: None) -> None:
    """`command.check` thật sự so model ↔ DB (để test trên không pass rỗng)."""
    command.upgrade(alembic_config(), "0003")
    run("DROP INDEX ix_package_warehouse_status_status_changed_at")

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(alembic_config())
