"""Hợp đồng API rút từ 02-tech-spec.md §6 (v0.4) — nguồn để so với `/openapi.json` sinh từ FastAPI.

Mỗi API-xx: method, path (không gồm tiền tố `/api/v1`), mã thành công, các trường response bắt buộc phải có
(đường dẫn chấm; `[]` = phần tử mảng) và giá trị enum 02 nêu (phải nằm trong enum của schema).
Đổi contract → sửa 02 §6 trước (architect), rồi sửa bảng này.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Api:
    id: str
    method: str
    path: str
    status: int
    fields: tuple[str, ...] = ()
    enums: dict[str, frozenset[str]] = field(default_factory=dict)
    request_fields: tuple[str, ...] = ()


def _e(*values: str) -> frozenset[str]:
    return frozenset(values)


# API-10 dùng lại trong API-11..14 (`state`) và WS-01 `station.state`.
STATE_FIELDS = (
    "station.id",
    "station.name",
    "station.kind",
    "station.work_mode",
    "station.operator_name",
    "state",
    "cameras[].role",
    "cameras[].status",
    "tray.codes",
    "tray.match",
    "tray.updated_at",
    "session.id",
    "session.status",
    "session.started_at",
    "session.flags",
    "session.package.id",
    "session.package.tracking_number",
    "session.package.order.platform",
    "session.package.order.platform_order_sn",
    "session.package.order.buyer_note",
    "session.package.items[].product_name",
    "session.package.items[].variation",
    "session.package.items[].quantity",
    "session.package.items[].image_url",
    "session.mismatch.source",
    "session.mismatch.expected",
    "session.mismatch.actual",
    "session.warn_at",
    "session.abandon_at",
    # Phase 2 (02 §6.2 API-10 mở rộng).
    "session.type",
    "session.operator_name",
    "session.package.items[].order_item_id",
    "session.return_case.id",
    "session.return_case.code",
    "session.return_case.kind",
    "session.return_case.status",
    "session.return_case.platform_return_sn",
    "session.return_case.return_tracking_number",
    "session.return_case.reason",
    "session.return_case.reason_text",
    "session.return_case.reason_label",
    "session.return_case.package_count",
    "session.return_case.received_count",
    "session.inspection.conclusion",
    "session.inspection.note",
    "session.inspection.saved_at",
    "session.inspection.lines_mode",
    "session.inspection.lines[].order_item_id",
    "session.inspection.lines[].product_name",
    "session.inspection.lines[].variation",
    "session.inspection.lines[].image_url",
    "session.inspection.lines[].quantity_sent",
    "session.inspection.lines[].quantity_requested",
    "session.inspection.lines[].quantity_received",
    "session.inspection.lines[].condition",
    "session.inspection.lines[].note",
    "session.snapshots[].id",
    "session.snapshots[].kind",
    "session.snapshots[].taken_at",
    "session.snapshots[].url",
    "session.pack_reference.session_id",
    "session.pack_reference.ended_at",
    "session.pack_reference.station_name",
    "session.pack_reference.clips[].id",
    "session.pack_reference.clips[].camera_role",
    "session.pack_reference.clips[].status",
    "session.pack_reference.snapshot.id",
    "session.pack_reference.snapshot.url",
    "today_return_count",
    "today_return_issue_count",
    "approval_request.id",
    "approval_request.type",
    "approval_request.tracking_number",
    "approval_request.created_at",
    "today_count",
    "server_time",
)
STATE_ENUMS = {
    "station.kind": _e("PACK", "RETURN", "BOTH"),
    "station.work_mode": _e("PACK", "RETURN"),
    "state": _e("READY", "PACKING", "MISMATCH", "WAITING_APPROVAL", "INSPECTING"),
    "session.type": _e("PACK", "RETURN"),
    "session.inspection.lines_mode": _e("FULL", "REFERENCE"),
    "session.inspection.conclusion": _e("OK", "DAMAGED", "MISSING_ITEM", "WRONG_ITEM", "EMPTY_BOX", "OTHER"),
    "session.snapshots[].kind": _e("MANUAL", "PACK_CLOSE"),
    "tray.match": _e("MATCH", "NOT_SEEN", "DIFFERENT", "MULTIPLE", "UNAVAILABLE"),
    "cameras[].role": _e("CAM1", "CAM2"),
    "cameras[].status": _e("ONLINE", "OFFLINE"),
    "session.mismatch.source": _e("SCAN", "CAM2"),
    "approval_request.type": _e("MISMATCH", "ASSIST", "REPACK"),
}


def _prefixed(prefix: str, names: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(f"{prefix}.{n}" for n in names)


def _prefixed_enums(prefix: str, enums: dict[str, frozenset[str]]) -> dict[str, frozenset[str]]:
    return {f"{prefix}.{k}": v for k, v in enums.items()}


PAGE = ("page", "page_size", "total")
# `closed_session` của API-11 (02 §6.2) — cũng là WS-01 `alert SESSION_AUTO_CLOSED`.
CLOSED_SESSION = (
    "id",
    "type",
    "tracking_number",
    "flags",
    "conclusion",
    "claim_code",
    "package_status",
    "return_case_status",
)

# Item hồ sơ hàng hoàn (02 §6.2 API-110) — dùng lại trong API-111.
RETURN_CASE_ITEM = (
    "id",
    "code",
    "kind",
    "status",
    "order.id",
    "order.platform_order_sn",
    "packages[].id",
    "packages[].tracking_number",
    "packages[].warehouse_status",
    "return_tracking_number",
    "reason_label",
    "reported_at",
    "expected_since",
    "waiting_days",
    "received_at",
    "conclusion",
    "claims[].id",
    "claims[].code",
    "claims[].status",
    "merged_into.id",
    "merged_into.code",
)
RETURN_CASE_ENUMS = {
    "kind": _e("FAILED_DELIVERY", "BUYER_RETURN", "REFUND_ONLY", "UNANNOUNCED", "UNIDENTIFIED"),
    "status": _e(
        "EXPECTED",
        "INSPECTING",
        "PARTIALLY_RECEIVED",
        "RECEIVED_OK",
        "RECEIVED_ISSUE",
        "MISSING",
        "CANCELLED",
        "NO_PARCEL",
    ),
}

# Item cảnh báo lệch (02 §6.2 API-120) — dùng lại trong API-121 / 122.
RECON_ALERT_ITEM = (
    "id",
    "rule",
    "br",
    "severity",
    "status",
    "package.id",
    "package.tracking_number",
    "package.warehouse_status",
    "package.platform_status",
    "context",
    "detected_at",
    "closed_at",
    "resolution.action",
    "resolution.note",
    "resolution.by.id",
    "resolution.by.display_name",
    "resolution.at",
    "resolution.to_status",
    "resolution.claim_id",
    "allowed_status_targets",
)
# Hồ sơ khiếu nại (02 §6.2 API-130..135) — chi tiết dùng lại trong API-131, 133, 134.
CLAIM_ENUMS = {
    "type": _e(
        "DAMAGED", "MISSING_ITEM", "WRONG_ITEM", "EMPTY_BOX", "OTHER", "BUYER_CLAIM", "LOST_IN_TRANSIT"
    ),
    "counterparty": _e("PLATFORM", "CARRIER"),
    "status": _e("NEW", "SUBMITTED", "WAITING", "WON", "LOST", "CLOSED"),
    "source": _e("AUTO_RETURN", "MANUAL", "RECON", "LEGACY_HOLD"),
}
CLAIM_DETAIL = (
    "id",
    "code",
    "type",
    "counterparty",
    "status",
    "source",
    "version",
    "package.id",
    "package.tracking_number",
    "package.warehouse_status",
    "order.id",
    "order.platform_order_sn",
    "return_case.id",
    "return_case.code",
    "return_case.kind",
    "return_case.return_tracking_number",
    "owner.id",
    "owner.display_name",
    "deadline_at",
    "deadline_source",
    "platform_claim_ref",
    "recovered_amount",
    "close_reason",
    "created_at",
    "closed_at",
    "evidence[].id",
    "evidence[].kind",
    "evidence[].auto",
    "evidence[].session.id",
    "evidence[].session.type",
    "evidence[].session.status",
    "evidence[].session.station_name",
    "evidence[].session.operator_name",
    "evidence[].session.started_at",
    "evidence[].session.ended_at",
    "evidence[].session.flags",
    "evidence[].session.clips[].id",
    "evidence[].session.clips[].camera_role",
    "evidence[].session.clips[].status",
    "evidence[].session.clips[].sha256",
    "evidence[].session.clips[].deleted_at",
    "evidence[].snapshot.id",
    "evidence[].snapshot.kind",
    "evidence[].snapshot.taken_at",
    "evidence[].snapshot.url",
    "other_sessions[].id",
    "other_sessions[].type",
    "other_sessions[].status",
    "other_sessions[].started_at",
    "missing",
    "notes[].id",
    "notes[].kind",
    "notes[].text",
    "notes[].author.id",
    "notes[].author.display_name",
    "notes[].at",
    "allowed_transitions",
)
CLAIM_DETAIL_ENUMS = {
    **CLAIM_ENUMS,
    "deadline_source": _e("PLATFORM", "DEFAULT", "MANUAL"),
    "evidence[].kind": _e("SESSION", "SNAPSHOT"),
    "missing[]": _e("NO_PACK_CLIP", "PACK_CLIP_DELETED", "RETURN_CLIP_PENDING"),
    "notes[].kind": _e("NOTE", "STATUS_CHANGE", "SYSTEM"),
}
APPROVAL_ITEM = (
    "id",
    "type",
    "status",
    "station.id",
    "station.name",
    "session_id",
    "tracking_number",
    "context",  # dict tự do trong OpenAPI; khóa expected/actual/source/tray_match kiểm ở test runtime
    "created_at",
    "decision",
    "decided_by.id",
    "decided_by.display_name",
    "decided_at",
    "note",
    "session_type",  # Phase 2 (02 API-20)
    "operator_name",
)
STATION_ITEM = (
    "id",
    "name",
    "is_active",
    "account.id",
    "account.username",
    "cameras[].id",
    "cameras[].role",
    "cameras[].rtsp_url_masked",
    "cameras[].status",
    "cameras[].roi",
    "kind",
    "work_mode",
    "operator_name",
)
USER_ITEM = (
    "id",
    "username",
    "display_name",
    "role",
    "is_active",
    "station.id",
    "station.name",
    "created_at",
)
EXPORT_FIELDS = (
    "id",
    "session_id",
    "layout",
    "status",
    "progress",
    "sha256",
    "source_clip_sha256",
    "files.video",
    "files.info",
    "expires_at",
)

CONTRACT: tuple[Api, ...] = (
    Api(
        "API-01",
        "POST",
        "/auth/login",
        200,
        (
            "access_token",
            "expires_in",
            "user.id",
            "user.username",
            "user.display_name",
            "user.role",
            "user.station.id",
            "user.station.name",
        ),
        {"user.role": _e("ADMIN", "SUPERVISOR", "CSKH", "STATION")},
        request_fields=("username", "password", "client"),
    ),
    Api("API-02", "POST", "/auth/refresh", 200, ("access_token", "expires_in"), request_fields=("client",)),
    Api("API-03", "POST", "/auth/logout", 204),
    Api(
        "API-04",
        "GET",
        "/me",
        200,
        (
            "id",
            "username",
            "display_name",
            "role",
            "station.id",
            "station.name",
            "station.kind",
            "station.work_mode",
            "permissions",
        ),
    ),
    Api("API-10", "GET", "/station/state", 200, STATE_FIELDS, STATE_ENUMS),
    Api(
        "API-11",
        "POST",
        "/station/scan",
        200,
        (
            "outcome",
            "alert.code",
            "alert.message",
            "alert.data",
            *_prefixed("state", STATE_FIELDS),
            *_prefixed("closed_session", CLOSED_SESSION),
        ),
        {
            "outcome": _e("SESSION_OPENED", "SESSION_COMPLETED", "MISMATCH", "ALERT", "IGNORED"),
            "alert.code": _e(
                "ORDER_CANCELLED",
                "ALREADY_PACKED",
                "ALREADY_HANDED_OVER",
                "INVALID_CODE",
                "PACKED_ELSEWHERE_IN_PROGRESS",
                "OPERATOR_REQUIRED",
                "RETURN_NOT_FOUND",
                "RETURN_ALREADY_RECEIVED",
                "RETURN_MULTIPLE_PACKAGES",
                "NOT_SHIPPED",
                "RETURN_IN_PROGRESS_ELSEWHERE",
                "INSPECTION_REQUIRED",
                "RETURN_CODE_DIFFERENT",
            ),
            **_prefixed_enums("state", STATE_ENUMS),
            "closed_session.type": _e("PACK", "RETURN"),
        },
        request_fields=("code", "client_scan_id"),
    ),
    Api(
        "API-12",
        "POST",
        "/station/sessions/{session_id}/cancel",
        200,
        _prefixed("state", STATE_FIELDS),
        request_fields=("reason", "note"),
    ),
    Api(
        "API-13",
        "POST",
        "/station/approval-requests",
        201,
        (
            "approval_request.id",
            "approval_request.type",
            "approval_request.status",
            "approval_request.tracking_number",
            "approval_request.created_at",
            *_prefixed("state", STATE_FIELDS),
        ),
        request_fields=("type", "session_id", "tracking_number"),
    ),
    Api(
        "API-14",
        "POST",
        "/station/approval-requests/{approval_id}/withdraw",
        200,
        _prefixed("state", STATE_FIELDS),
    ),
    Api(
        "API-15",
        "GET",
        "/station/sessions/recent",
        200,
        _prefixed(
            "items[]",
            (
                "id",
                "tracking_number",
                "status",
                "flags",
                "started_at",
                "ended_at",
                "type",
                "conclusion",
                "claim_code",
                "clips[].id",
                "clips[].camera_role",
                "clips[].status",
            ),
        ),
    ),
    Api(
        "API-20",
        "GET",
        "/approval-requests",
        200,
        (*PAGE, *_prefixed("items[]", APPROVAL_ITEM)),
        {
            "items[].type": _e("MISMATCH", "ASSIST", "REPACK"),
            "items[].status": _e("PENDING", "RESOLVED", "WITHDRAWN"),
        },
    ),
    Api(
        "API-21",
        "POST",
        "/approval-requests/{approval_id}/decision",
        200,
        (
            "approval_request.id",
            "approval_request.status",
            "approval_request.decision",
            "approval_request.decided_by.id",
            "approval_request.decided_by.display_name",
            "approval_request.decided_at",
        ),
        request_fields=("action", "note"),
    ),
    Api(
        "API-30",
        "GET",
        "/packages",
        200,
        (
            *PAGE,
            *_prefixed(
                "items[]",
                (
                    "id",
                    "tracking_number",
                    "platform_order_sn",
                    "warehouse_status",
                    "platform_status",
                    "source",
                    "last_session.station_name",
                    "last_session.ended_at",
                    "has_clip",
                ),
            ),
        ),
    ),
    Api(
        "API-31",
        "GET",
        "/packages/{package_id}",
        200,
        (
            "id",
            "tracking_number",
            "warehouse_status",
            "platform_logistics_status",
            "verified",
            "order.id",
            "order.platform",
            "order.platform_order_sn",
            "order.platform_status",
            "order.buyer_note",
            "order.source",
            "order.items[].product_name",
            "order.items[].variation",
            "order.items[].quantity",
            "order.items[].image_url",
            *_prefixed(
                "sessions[]",
                (
                    "id",
                    "status",
                    "station_name",
                    "started_at",
                    "ended_at",
                    "duration_s",
                    "flags",
                    "cancel_reason",
                    "note",
                    "clips[].id",
                    "clips[].camera_role",
                    "clips[].status",
                    "clips[].sha256",
                    "clips[].duration_s",
                    "clips[].held",
                    "clips[].retention_until",
                    "clips[].deleted_at",
                    "clips[].flags",
                ),
            ),
            "timeline[].at",
            "timeline[].source",
            "timeline[].from_status",
            "timeline[].to_status",
            "timeline[].actor",
        ),
    ),
    Api(
        "API-100",
        "PUT",
        "/station/work-mode",
        200,
        _prefixed("state", STATE_FIELDS),
        request_fields=("work_mode",),
    ),
    Api(
        "API-101", "PUT", "/station/operator", 200, _prefixed("state", STATE_FIELDS), request_fields=("name",)
    ),
    Api(
        "API-102",
        "PUT",
        "/station/sessions/{session_id}/inspection",
        200,
        (
            "inspection.conclusion",
            "inspection.note",
            "inspection.saved_at",
            "inspection.lines_mode",
            "inspection.lines[].order_item_id",
            "inspection.lines[].product_name",
            "inspection.lines[].variation",
            "inspection.lines[].image_url",
            "inspection.lines[].quantity_sent",
            "inspection.lines[].quantity_requested",
            "inspection.lines[].quantity_received",
            "inspection.lines[].condition",
            "inspection.lines[].note",
        ),
        {"inspection.conclusion": _e("OK", "DAMAGED", "MISSING_ITEM", "WRONG_ITEM", "EMPTY_BOX", "OTHER")},
        request_fields=("conclusion", "note", "lines"),
    ),
    Api(
        "API-103",
        "POST",
        "/station/sessions/{session_id}/snapshots",
        201,
        (
            "snapshot.id",
            "snapshot.kind",
            "snapshot.camera_role",
            "snapshot.taken_at",
            "snapshot.sha256",
            "snapshot.url",
        ),
        {"snapshot.kind": _e("MANUAL", "PACK_CLOSE"), "snapshot.camera_role": _e("CAM1")},
    ),
    Api("API-106", "GET", "/media/snapshots/{snapshot_id}", 200),
    Api(
        "API-104",
        "GET",
        "/station/return-lookup",
        200,
        (
            "items[].package_id",
            "items[].tracking_number",
            "items[].platform_order_sn",
            "items[].warehouse_status",
            "items[].return_case.id",
            "items[].return_case.code",
            "items[].return_case.kind",
            "items[].return_case.status",
            "items[].return_case.return_tracking_number",
            "items[].can_open",
            "items[].blocked_reason",
            "platform_checked",
        ),
    ),
    Api(
        "API-122",
        "POST",
        "/packages/{package_id}/warehouse-status",
        200,
        (
            "package.id",
            "package.tracking_number",
            "package.warehouse_status",
            *_prefixed("recon_alert", RECON_ALERT_ITEM),
        ),
        {
            "recon_alert.severity": _e("HIGH", "MEDIUM", "LOW"),
            "recon_alert.status": _e("OPEN", "RESOLVED", "AUTO_RESOLVED"),
        },
        request_fields=("to_status", "reason", "recon_alert_id"),
    ),
    Api(
        "API-110",
        "GET",
        "/returns",
        200,
        (
            *PAGE,
            *_prefixed("items[]", RETURN_CASE_ITEM),
            "tab_counts.EXPECTED",
            "tab_counts.MISSING",
            "tab_counts.RECEIVED",
            "tab_counts.NO_PARCEL",
            "tab_counts.UNIDENTIFIED",
        ),
        _prefixed_enums("items[]", RETURN_CASE_ENUMS),
    ),
    Api(
        "API-111",
        "GET",
        "/returns/{case_id}",
        200,
        (
            *RETURN_CASE_ITEM,
            "platform_return_sn",
            "platform_status",
            "needs_parcel",
            "reason",
            "reason_text",
            "seller_due_at",
            "source",
            "requested_items[].order_item_id",
            "requested_items[].product_name",
            "requested_items[].variation",
            "requested_items[].quantity",
            "sessions[].id",
            "sessions[].package_id",
            "sessions[].status",
            "sessions[].station_name",
            "sessions[].operator_name",
            "sessions[].started_at",
            "sessions[].ended_at",
            "sessions[].conclusion",
        ),
        {**RETURN_CASE_ENUMS, "source": _e("PLATFORM", "WAREHOUSE")},
    ),
    Api(
        "API-130",
        "GET",
        "/claims",
        200,
        (
            *PAGE,
            *_prefixed(
                "items[]",
                (
                    "id",
                    "code",
                    "type",
                    "counterparty",
                    "status",
                    "source",
                    "package.id",
                    "package.tracking_number",
                    "order.platform_order_sn",
                    "owner.id",
                    "owner.display_name",
                    "deadline_at",
                    "due_soon",
                    "overdue",
                    "created_at",
                ),
            ),
            *(f"status_counts.{s}" for s in ("NEW", "SUBMITTED", "WAITING", "WON", "LOST", "CLOSED")),
        ),
        _prefixed_enums("items[]", CLAIM_ENUMS),
    ),
    Api(
        "API-131",
        "POST",
        "/claims",
        201,
        CLAIM_DETAIL,
        CLAIM_DETAIL_ENUMS,
        request_fields=("package_id", "type", "counterparty", "note", "return_case_id", "recon_alert_id"),
    ),
    Api("API-132", "GET", "/claims/{claim_id}", 200, CLAIM_DETAIL, CLAIM_DETAIL_ENUMS),
    Api(
        "API-133",
        "PATCH",
        "/claims/{claim_id}",
        200,
        CLAIM_DETAIL,
        CLAIM_DETAIL_ENUMS,
        request_fields=(
            "version",
            "status",
            "platform_claim_ref",
            "owner_user_id",
            "deadline_at",
            "recovered_amount",
            "reason",
        ),
    ),
    Api(
        "API-134",
        "PUT",
        "/claims/{claim_id}/evidence",
        200,
        CLAIM_DETAIL,
        CLAIM_DETAIL_ENUMS,
        request_fields=("version", "session_ids", "snapshot_ids", "note"),
    ),
    Api(
        "API-135",
        "POST",
        "/claims/{claim_id}/notes",
        201,
        ("id", "kind", "text", "author.id", "author.display_name", "at"),
        {"kind": _e("NOTE", "STATUS_CHANGE", "SYSTEM")},
        request_fields=("text",),
    ),
    Api(
        "API-32",
        "GET",
        "/reports/daily",
        200,
        (
            "date",
            "counts.packed",
            "counts.had_mismatch",
            "counts.abandoned",
            "counts.cancelled",
            "counts.packed_not_handed_over",
            "counts.cancelled_after_pack",
            "stations[].id",
            "stations[].name",
            "stations[].state",
            "stations[].tracking_number",
            "stations[].cameras[].role",
            "stations[].cameras[].status",
            "stations[].last_scan_at",
            "attention",  # mỗi kind một dạng (dict tự do); `kind` kiểm ở test runtime
        ),
    ),
    Api("API-40", "GET", "/clips/{clip_id}/play-url", 200, ("url", "expires_at")),
    Api("API-41", "GET", "/media/clips/{clip_id}", 200),
    Api(
        "API-42",
        "PUT",
        "/clips/{clip_id}/hold",
        200,
        ("id", "held", "held_by.id", "held_by.display_name", "held_at", "retention_until"),
        request_fields=("held",),
    ),
    Api(
        "API-43",
        "POST",
        "/sessions/{session_id}/exports",
        202,
        ("id", "status", "progress"),
        {"status": _e("QUEUED")},
        request_fields=("layout",),
    ),
    Api(
        "API-44",
        "GET",
        "/exports/{export_id}",
        200,
        EXPORT_FIELDS,
        {"status": _e("QUEUED", "READY", "FAILED")},
    ),
    Api("API-45", "GET", "/media/exports/{export_id}/{file}", 200),
    Api("API-46", "POST", "/sessions/{session_id}/clips/rebuild", 202, ("queued",)),
    Api(
        "API-50",
        "POST",
        "/imports",
        201,
        (
            "id",
            "status",
            "file_name",
            "counts.new",
            "counts.updated",
            "counts.skipped",
            "counts.error",
            "errors[].row",
            "errors[].column",
            "errors[].message",
            "sample[].row",
            "sample[].tracking_number",
            "sample[].platform_order_sn",
            "sample[].product_name",
            "sample[].variation",
            "sample[].quantity",
            "sample[].action",
            "expires_at",
        ),
        {"sample[].action": _e("NEW", "UPDATE", "SKIP")},
    ),
    Api("API-51", "POST", "/imports/{import_id}/commit", 200, ("id", "status", "counts.new", "counts.error")),
    Api(
        "API-52",
        "GET",
        "/imports",
        200,
        (
            *PAGE,
            *_prefixed(
                "items[]",
                (
                    "id",
                    "status",
                    "file_name",
                    "counts",
                    "created_by.id",
                    "created_by.display_name",
                    "created_at",
                    "committed_at",
                ),
            ),
        ),
    ),
    Api("API-53", "GET", "/imports/template", 200),
    Api("API-54", "GET", "/imports/{import_id}/file", 200),
    Api("API-60 list", "GET", "/stations", 200, _prefixed("items[]", STATION_ITEM)),
    Api("API-60 get", "GET", "/stations/{station_id}", 200, STATION_ITEM),
    Api(
        "API-60 create",
        "POST",
        "/stations",
        201,
        STATION_ITEM,
        {"kind": _e("PACK", "RETURN", "BOTH")},
        request_fields=("name", "account_user_id", "kind"),
    ),
    Api(
        "API-60 patch",
        "PATCH",
        "/stations/{station_id}",
        200,
        STATION_ITEM,
        request_fields=("name", "is_active", "account_user_id", "kind"),
    ),
    Api(
        "API-61",
        "PUT",
        "/stations/{station_id}/cameras/{role}",
        200,
        ("id", "role", "status", "roi"),
        request_fields=("rtsp_url", "username", "password"),
    ),
    Api(
        "API-62",
        "POST",
        "/cameras/test",
        200,
        ("ok", "snapshot", "clock_offset_ms"),
        request_fields=("rtsp_url", "username", "password"),
    ),
    Api("API-63", "GET", "/cameras/{camera_id}/snapshot", 200),
    Api(
        "API-64",
        "PUT",
        "/cameras/{camera_id}/roi",
        200,
        ("id", "role", "status", "roi.x", "roi.y", "roi.w", "roi.h"),
        request_fields=("x", "y", "w", "h"),
    ),
    Api(
        "API-65",
        "GET",
        "/live",
        200,
        (
            "stations[].id",
            "stations[].name",
            "stations[].cameras[].id",
            "stations[].cameras[].role",
            "stations[].cameras[].status",
            "stations[].cameras[].whep_url",
        ),
    ),
    Api(
        "API-70",
        "GET",
        "/shops",
        200,
        _prefixed(
            "items[]",
            (
                "id",
                "platform",
                "name",
                "auth_status",
                "auth_expires_at",
                "last_synced_at",
                "today_synced_orders",
                "last_error",
            ),
        ),
    ),
    Api("API-71", "POST", "/shops/shopee/auth-url", 200, ("url",)),
    Api("API-72", "GET", "/shops/shopee/callback", 302),
    Api("API-73", "POST", "/shops/{shop_id}/sync", 202, ("queued",)),
    Api(
        "API-80 get",
        "GET",
        "/settings",
        200,
        ("retention_raw_days", "retention_clip_days", "session_warn_minutes", "session_abandon_minutes"),
    ),
    Api(
        "API-80 put",
        "PUT",
        "/settings",
        200,
        ("retention_raw_days", "retention_clip_days", "session_warn_minutes", "session_abandon_minutes"),
        request_fields=(
            "retention_raw_days",
            "retention_clip_days",
            "session_warn_minutes",
            "session_abandon_minutes",
        ),
    ),
    Api(
        "API-81",
        "GET",
        "/system/health",
        200,
        (
            "db",
            "redis",
            "mediamtx",
            "disk.total_bytes",
            "disk.used_bytes",
            "disk.percent",
            "cameras[].id",
            "cameras[].station_name",
            "cameras[].role",
            "cameras[].status",
            "cameras[].clock_offset_ms",
            "cameras[].last_seen_at",
            "sync[].shop_id",
            "sync[].last_success_at",
            "sync[].last_error",
        ),
        {"db": _e("OK", "ERROR"), "redis": _e("OK", "ERROR"), "mediamtx": _e("OK", "ERROR")},
    ),
    Api("API-90 list", "GET", "/users", 200, (*PAGE, *_prefixed("items[]", USER_ITEM))),
    Api(
        "API-90 create",
        "POST",
        "/users",
        201,
        USER_ITEM,
        request_fields=("username", "display_name", "role", "password"),
    ),
    Api(
        "API-90 patch",
        "PATCH",
        "/users/{user_id}",
        200,
        USER_ITEM,
        request_fields=("display_name", "role", "is_active", "password"),
    ),
    Api("API-91", "POST", "/users/{user_id}/revoke-sessions", 204),
    Api(
        "API-92",
        "GET",
        "/audit-logs",
        200,
        (
            *PAGE,
            "items[].at",
            "items[].user.id",
            "items[].user.display_name",
            "items[].action",
            "items[].object_type",
            "items[].object_id",
        ),
    ),
)
